# Generated by Django 5.0.7 on 2024-07-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='apellido_personal',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='nombre_personal',
        ),
        migrations.AddField(
            model_name='personal',
            name='apellido',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
