# Generated by Django 5.0.7 on 2024-07-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0004_remove_personal_apellido_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/imagenes'),
        ),
    ]
