# Generated by Django 5.0.7 on 2024-07-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0005_personal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
