# Generated by Django 5.0.7 on 2024-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0006_alter_personal_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes'),
        ),
    ]
