# Generated by Django 5.0.7 on 2024-08-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0007_alter_personal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
