# Generated by Django 5.0.7 on 2024-08-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0008_alter_personal_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
