# Generated by Django 5.0.7 on 2024-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0009_alter_personal_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='imagen',
        ),
    ]
