# Generated by Django 5.0.7 on 2024-08-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0010_remove_personal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
