# Generated by Django 5.0.7 on 2024-08-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0011_alter_personal_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
