# Generated by Django 5.0.7 on 2024-08-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionalidad', '0014_alter_personal_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='activo',
        ),
    ]
